### ISSUE TITLE
How to add "systemIntent"s  to the Response with this Libary?

### ISSUE THREAD

**Issue by MTRNord** [leboncoin/dialogflow-go-webhook#1]
Hi I want to do Google Auth with this and therefor need to add a systemIntent to the payload. (See: https://developers.google.com/actions/build/json/dialogflow-webhook-json#dialogflow-response-body )

Is there any way to do it?

**Comment by depado** [comment]
Hey.
Since the `v2` API is now stable, Dialogflow has released a Go SDK.
You can [find it here](https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/dialogflow/apiv2), maybe this can solve your issue ?
Have a look and tell me if you find what you want in there, if not, I'll have a closer look on how to implement it.

**Comment by MTRNord** [comment]
@Depado hi thanks for the link. I will Take a look at that official Code :)

**Comment by depado** [comment]
You're welcome :ok_hand:

**Comment by depado** [comment]
I wrote an [article on how to use the protobuf definition and generated Go code to handle webhooks](https://medium.com/leboncoin-engineering-blog/dialogflow-webhook-golang-and-protobuf-6269269f17f6). This will probably solve your issue ;)
