### ISSUE TITLE
FollowupEventInput in fulfillment

### ISSUE THREAD

**Issue by dfischer** [leboncoin/dialogflow-go-webhook#2]
Seems like we can add a type here, just leave params open interface for others to specify?

**Comment by depado** [comment]
Hey there :wave: 
This project will be deprecated soon because Dialogflow released a Go SDK for their v2 version [here](https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/dialogflow/apiv2). 

Please tell me if that suits your needs :+1:

**Comment by dfischer** [comment]
@Depado It seems their examples are lacking and I used yours because it basically had a fulfillment example ready to go. I will check their code and see if there's a fulfillment example. So far I haven't found one.

Thanks!

**Comment by depado** [comment]
I'm currently writing an article on how to use the protobuf definition [which you can find here](https://godoc.org/google.golang.org/genproto/googleapis/cloud/dialogflow/v2) to handle your fulfillment. 
Indeed, the SDK can be used to control Dialogflow's behavior (training, pushing data, setting up the agents), but doesn't provide an easy way to handle a fulfillment payload. That's why there's a protobuf definition.

Anyway I'll merge your PR ! Thanks for your contribution !

![thanks](https://media.giphy.com/media/4lpctAAV9Azpm/giphy.gif)

**Comment by dfischer** [comment]
@Depado sounds like an interesting article. I'd love to see it when you have it. :)
